encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("index.html", views.index, name="index"),
    path("wiki/<str:entry_name>", views.display_entry, name="display_entry"),
    path("search/", views.search, name="search"),
    path("create_page/", views.create_page, name="create_page"),
    path("edit_page/", views.edit_page, name="edit_page"),
    path("random_page/", views.random_page, name="random_page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from markdown2 import markdown
from . import util
from random import randint


def index(request):
    return render(request, 'encyclopedia/index.html', {
        "entries": util.list_entries()
    })


def display_entry(request, entry_name):
    # Get entry data
    entry = util.get_entry(entry_name)

    # Check if entry is found
    if entry:
        return render(request, "encyclopedia/entry.html", {
            'title': util.get_entry_title(entry_name),
            'entry': markdown(entry)
        })
    # if entry is not found return error
    else:
        return render(request, "encyclopedia/error.html", {
            "message": "Page Not Found"
        })


def search(request):
    # Get q arugument and clean it
    q = request.GET.get('q').strip().lower()

    # if entry is found display it
    if util.get_entry(q):
        return display_entry(request, q)
    # if not found check if it's a sub entry
    else:
        # List all available entries
        available_entries = util.list_entries()
        # q_sub is a set to store all entries in which q is a substring
        q_sub = set()

        # Iterate over available entries and check if q is a sub entry
        # If yes add to q_sub
        for entry in available_entries:
            if q in entry.lower():
                q_sub.add(entry)

        # If there is only on matched entity at least
        # Render search_result.html to display a list of matches
        if len(q_sub):
            return render(request, "encyclopedia/search_result.html", {
                "entries": q_sub
            })
        # If there is no match render error
        else:
            return render(request, "encyclopedia/error.html", {
                "message": "No Results!"
            })


def create_page(request):
    # If method is POST
    if request.method == "POST":
        # Retrive Data
        title = request.POST.get('title')
        content = request.POST.get('content')

        # If Entry title is found retrun error
        if util.get_entry(title):
            return render(request, "encyclopedia/error.html", {
                "message": "Page already exists!"
            })

        # Save entry
        util.save_entry(title, content)
        # Display entry page
        return display_entry(request, title)

    # If method is GET render create_page.html
    return render(request, "encyclopedia/create_page.html")


def edit_page(request):
    if request.POST.get("edited") == 'false':
        title = request.POST.get('title')
        return render(request, "encyclopedia/edit_page.html", {
            "title": title,
            "content": util.get_entry(title)
        })
    else:
        new_title = request.POST.get('new_title')
        old_title = request.POST.get('old_title')

        if new_title != old_title:
            util.delete_entry(request.POST.get('old_title'))

        print(request.POST.get('new_content'))
        util.save_entry(new_title, request.POST.get('new_content'))

        return display_entry(request, new_title)


# Return random entry page
def random_page(request):
    available_entries = util.list_entries()
    random_index = randint(0, len(available_entries)-1)

    return display_entry(request, available_entries[random_index])

encyclopedia/templates/encyclopedia/create_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia: Create New Page
{% endblock %}

{% block body %}
<h2 id="create-header">Create New Page</h2>
<form action="{% url 'encyclopedia:create_page' %}" class="form mb-3" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name=title required autocomplete="off">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Content</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" name="content"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Create Page</button>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia: Edit {{ title }}
{% endblock %}

{% block body %}
<h2 id="create-header">Edit {{ title }} Page</h2>

<form action="{% url 'encyclopedia:edit_page' %}" class="form mb-3" method="post">
    {% csrf_token %}
    <input type="text" hidden name="edited" value="true">

    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name="new_title" value="{{ title }}" required
            autocomplete="off">
        <input type="text" hidden name="old_title" value="{{ title }}">
    </div>

    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Content</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="10"
            name="new_content">{{ content }}</textarea>
    </div>

    <button type="submit" class="btn btn-primary">Edit {{ title }} Page</button>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<header>
    <form action="{% url 'encyclopedia:edit_page' %}" method="post">
        {% csrf_token %}
        <input type="text" hidden name="edited" value="false">
        <input hidden type="text" name="title" value="{{ title }}">
        <input type="submit" id="edit-btn" value="Edit Page">
    </form>
</header>
{{ entry|safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Not Found!
{% endblock %}

{% block body %}
<div class="error">{{ message }}</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li>
        <!-- <a href="wiki/{{ entry }}">{{ entry }}</a> -->
        <a href="{% url 'encyclopedia:display_entry' entry %}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'encyclopedia:search' %}">
                <input class="search" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off">
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:create_page' %}">Create New Page</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

encyclopedia/templates/encyclopedia/search_result.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
Encyclopedia: Search Results
{% endblock %}

{% block body %}
<h1>Search Results:</h1>

<ul>
    {% for entry in entries %}
    <li>
        <!-- <a href="wiki/{{ entry }}">{{ entry }}</a> -->
        <a href="{% url 'encyclopedia:display_entry' entry %}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}